plugin-enabled: false
grace-seconds: 600
initial-border-diameter: 1500.0
shrink-rate-fight: 0.5
shrink-rate-final: 1.5
final-fight-threshold: 10
min-border-diameter: 32.0
exempt-users:
  - "Recorder"
