plugin-enabled: false
grace-seconds: 600 //Grace Period time limit
initial-border-diameter: 1500.0 //Area of world under border
shrink-rate-fight: 0.5 //Shink rate after grace period
shrink-rate-final: 1.5 //Shrink rate after final fight required no. of players are there
final-fight-threshold: 10 //Amount of players required for final fight phase to start
min-border-diameter: 32.0 //Minimum size of border after shink
exempt-users: //Simply add the names of admins under here
  - "Recorder"
