# SurvivalGamesPlugin configuration
plugin-enabled: true
grace-seconds: 180
initial-border-diameter: 500.0
shrink-rate-fight: 1.0
shrink-rate-final: 2.0
final-fight-threshold: 2
min-border-diameter: 32.0
exempt-users:
  - "Recorder"

visuals:
  hardcore-hearts: true
